version: 2
updates:
- package-ecosystem: npm
  target_branch: dependencies
  directory: "/"
  schedule:
      interval: "daily"
      time: "09:00"
  open-pull-requests-limit: 10
  automerged_updates: yes
